// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt = require("bs-platform/lib/js/belt.js");
var Async = require("serbet/src/Async.bs.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var AsyncWrap = {
  let_: Async.mapAsync
};

var Id = Belt.Id;

var $$Array = Belt.$$Array;

var SortArray = Belt.SortArray;

var MutableQueue = Belt.MutableQueue;

var MutableStack = Belt.MutableStack;

var List = Belt.List;

var $$Range = Belt.$$Range;

var $$Set = Belt.$$Set;

var $$Map = Belt.$$Map;

var MutableSet = Belt.MutableSet;

var MutableMap = Belt.MutableMap;

var HashSet = Belt.HashSet;

var HashMap = Belt.HashMap;

var $$Option = Belt.$$Option;

var Result = Belt.Result;

var Int = Belt.Int;

var Float = Belt.Float;

var let_ = Async.let_;

var mapAsync = Async.mapAsync;

var async = Async.async;

var catchAsync = Async.catchAsync;

var asyncFromResult = Async.asyncFromResult;

var attemptMapAsync = Async.attemptMapAsync;

var Prometo;

var oMap = Belt_Option.map;

var $less$$great = Belt_Option.map;

var oFlatMap = Belt_Option.flatMap;

var $great$great$eq = Belt_Option.flatMap;

var mapd = Belt_Option.mapWithDefault;

var $pipe$pipe$pipe$pipe = Belt_Option.getWithDefault;

exports.Id = Id;
exports.$$Array = $$Array;
exports.SortArray = SortArray;
exports.MutableQueue = MutableQueue;
exports.MutableStack = MutableStack;
exports.List = List;
exports.$$Range = $$Range;
exports.$$Set = $$Set;
exports.$$Map = $$Map;
exports.MutableSet = MutableSet;
exports.MutableMap = MutableMap;
exports.HashSet = HashSet;
exports.HashMap = HashMap;
exports.$$Option = $$Option;
exports.Result = Result;
exports.Int = Int;
exports.Float = Float;
exports.let_ = let_;
exports.mapAsync = mapAsync;
exports.async = async;
exports.catchAsync = catchAsync;
exports.asyncFromResult = asyncFromResult;
exports.attemptMapAsync = attemptMapAsync;
exports.Prometo = Prometo;
exports.AsyncWrap = AsyncWrap;
exports.oMap = oMap;
exports.$less$$great = $less$$great;
exports.oFlatMap = oFlatMap;
exports.$great$great$eq = $great$great$eq;
exports.mapd = mapd;
exports.$pipe$pipe$pipe$pipe = $pipe$pipe$pipe$pipe;
/* Async Not a pure module */
